#!/bin/sh
# Runs prettier on all staged files

set -eu

die () {
	printf '\033[31mError: %s\033[m\n' "${1:-"Script $0 exited with unknown error"}"
	exit 1
}

# subshell to not clobber IFS
format_staged () (
	PRETTIER_BIN="backend/node_modules/.bin/prettier"

	[ "$#" -lt 1 ] && die "format_staged function expects at least 1 extension as an argument"
	command -v $PRETTIER_BIN 1>/dev/null 2>&1 || die "Please install prettier to run pre-commit hooks"

	IFS='|'
	if git diff --name-only --cached --diff-filter=d | \
		grep -E "\.($*)\$"                        | \
		tr '\n' '\0'                              | \
		xargs -r0 $PRETTIER_BIN --list-different 1>/dev/null; then
		all_good=1
	else
		all_good=0
	fi

	git diff --name-only --cached --diff-filter=d | \
		grep -E "\.($*)\$"                        | \
		tr '\n' '\0'                              | \
		xargs -r0 $PRETTIER_BIN --write

	if [ ! "$all_good" = "1" ]; then
		printf '\033[33m%s\033[m\n' "Warning: Not commiting since some files were formatted with prettier"
		printf '\033[33m%s\033[m\n' "         Run 'git add -u' to stage those files as well"
		printf '\033[33m%s\033[m\n' "         Commit again to force the commit (i.e. ignore files changed by prettier)"
		return 1
	fi
)

wrong_quotes () {
	printf '\033[33m%s\033[m\n' \
		'Wrong quoting style detected (only double quotes or backticks allowed)!' \
		'Fix it, and if there are false-positives left, run the following command to make an exception for them:' \
		"	script/find_quotes -n roff_squote roff_dquote squote >> script/quote_exceptions"

	if [ "${1:-}" = "enforce" ]; then
		false
	else
		: #This will never be enforced, as it would probably get annoying too quickly
		#printf "\033[33m%s\033[m\n" \
		#	"Not enforcing. This warning will turn into an error in the future."
	fi
}

# Check 1 - Ensure quoting style in comments (forbid single quote or roff/TeX style quotes (https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html))
! script/find_quotes roff_squote roff_dquote squote || wrong_quotes 'dont_enforce' # https://www.shellcheck.net/wiki/SC2251

# Check 2 - Format everything
format_staged ts js json css html md yaml yml

printf '\033[32m%s\033[m\n' "pre-commit hook finished without error"
