# Network settings
network.host: ${ELASTICSEARCH_HOST}
http.port: ${ELASTICSEARCH_PORT}

# Security settings
xpack.security.enabled: true

# SSL settings
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Performance settings
thread_pool.write.queue_size: 1000
indices.query.bool.max_clause_count: 4096

# Data retention settings
action.auto_create_index: .monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*,*
